name: Deploy Data to Public

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move data.json to public folder
        run: |
          mkdir -p public
          cp data.json public/data.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/data.json
          git commit -m "Deploy data.json to public folder"
          git push
