name: Update Data JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ 저장소에 "쓰기 권한" 부여

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Data JSON
        run: |
          echo '{"users": [{"name": "홍길동", "birth": "2000-01-01", "phone": "010-1234-5678", "address": "서울", "note": "테스트"}]}' > data.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update data.json via GitHub Actions"
          git push
