name: Update GitHub Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ GitHub Actions에서 저장소에 "쓰기 권한" 부여

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Modify JSON file
        run: |
          echo '{"users": [{"name": "홍길동", "birth": "2000-01-01", "phone": "010-1234-5678", "address": "서울", "note": "테스트"}]}' > data.json

      - name: Commit and Push Changes
        run: |
          git add data.json
          git commit -m "Update data.json via GitHub Actions"
          git push origin main
